name: "Lock Threads"

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'researchxxl'
    steps:
      - uses: dessant/lock-threads@89ae32b08ed1a541efecbab17912962a5e38981c # v6.0.2
        with:
          process-only: 'issues, prs'
          issue-inactive-days: "0"
          issue-lock-reason: ''
          pr-inactive-days: "0"
          pr-lock-reason: ''
          issue-comment: >
            🤖 This issue has been automatically locked because it was closed.
          pr-comment: >
            🤖 This pull request has been automatically locked because it was closed.
